name: let_tutor
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    localization:
        path: ./modules/localization

    cupertino_icons: ^1.0.2
    adaptive_theme: ^3.4.0
    flutter_bloc: ^8.1.3
    intl: ^0.18.1
    bloc: ^8.1.2
    collection: ^1.17.2
    flutter_localization: ^0.1.14
    intl_utils: ^2.8.4
    shared_preferences: ^2.2.1
    logger: ^2.0.2+1
    meta: ^1.9.1
    get_it: ^7.6.4
    injector: ^3.0.0
    injectable: ^2.3.0
    injectable_generator: ^2.4.0
    build_runner: ^2.4.6
    flutter_svg: ^2.0.7
    video_player: ^2.7.2
    visibility_detector: ^0.4.0+2
    youtube_player_iframe: ^4.0.4
    syncfusion_flutter_pdfviewer: ^23.1.39
    
    freezed_annotation: ^2.4.1
    json_annotation: ^4.8.1
    retrofit: ^4.0.2
    retrofit_generator: ^8.0.0
    dio: ^5.3.3
    easy_debounce: ^2.0.3
    jitsi_meet_wrapper: ^0.2.0+1
    file_picker: ^6.0.0
    image_picker: ^1.0.4
    im_stepper: ^1.0.1+1
    google_sign_in: ^6.1.6
    firebase_core: ^2.24.2
    flutter_facebook_auth: ^6.0.3
    firebase_auth: ^4.15.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    freezed: ^2.4.1
    json_serializable: ^6.7.1

flutter:
    assets:
        - assets/images/
        - assets/icons/
    uses-material-design: true
