// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlscwUjzQQVxyEgKzYYHDwIgnGS-TR-GA',
    appId: '1:743337691161:android:32c5fdbbab20c4f4238288',
    messagingSenderId: '743337691161',
    projectId: 'lettutor-69dc3',
    storageBucket: 'lettutor-69dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1icGhnWi-_bj6GJXTl2C-Wm_Lrva8NSs',
    appId: '1:743337691161:ios:d7a7fa406d8ce7e9238288',
    messagingSenderId: '743337691161',
    projectId: 'lettutor-69dc3',
    storageBucket: 'lettutor-69dc3.appspot.com',
    androidClientId: '743337691161-3q7tah1k0jsrjkbkp51qklvhdd8ek2v9.apps.googleusercontent.com',
    iosClientId: '743337691161-jc8eitp2o38knl4cri1aqtlrfcvlfa07.apps.googleusercontent.com',
    iosBundleId: 'com.example.letTutor',
  );
}
